
export const GET_VISUALS_DATA = 'GET_VISUALS_DATA';
export const GET_VISUALS_DATA_SUCCESS = 'GET_VISUALS_DATA_SUCCESS';
export const GET_VISUALS_DATA_ERROR = 'GET_VISUALS_DATA_ERROR';

export const GET_WRITERS_DATA = 'GET_WRITERS_DATA';
export const GET_WRITERS_DATA_SUCCESS = 'GET_WRITERS_DATA_SUCCESS';
export const GET_WRITERS_DATA_ERROR = 'GET_WRITERS_DATA_ERROR';

export const GET_STORYBOARDS_DATA = 'GET_STORYBOARDS_DATA';
export const GET_STORYBOARDS_DATA_SUCCESS = 'GET_STORYBOARDS_DATA_SUCCESS';
export const GET_STORYBOARDS_DATA_ERROR = 'GET_STORYBOARDS_DATA_ERROR';

export const GET_GRAPHIC_DESIGN_DATA = 'GET_GRAPHIC_DESIGN_DATA';
export const GET_GRAPHIC_DESIGN_DATA_SUCCESS = 'GET_GRAPHIC_DESIGN_DATA_SUCCESS';
export const GET_GRAPHIC_DESIGN_DATA_ERROR = 'GET_GRAPHIC_DESIGN_DATA_ERROR';

export const GET_EUROPEAN_TALENT_DATA = 'GET_EUROPEAN_TALENT_DATA';
export const GET_EUROPEAN_TALENT_DATA_SUCCESS = 'GET_EUROPEAN_TALENT_DATA_SUCCESS';
export const GET_EUROPEAN_TALENT_DATA_ERROR = 'GET_EUROPEAN_TALENT_DATA_ERROR';

export const GET_CORPORATE_DATA = 'GET_CORPORATE_DATA';
export const GET_CORPORATE_DATA_SUCCESS = 'GET_CORPORATE_DATA_SUCCESS';
export const GET_CORPORATE_DATA_ERROR = 'GET_CORPORATE_DATA_ERROR';
